name=UWB_DW1000_DW3000
version=1.0.1
author=Igor Levkov <levkov.igor@gmail.com>
maintainer=Igor Levkov <levkov.igor@gmail.com>
sentence=UWB library for DW1000 and DW3000
paragraph=UWB library with simple communication or distance measurement examples
category=Communication
url=https://github.com/levkovigor/UWB_DW1000_DW3000
architectures=*
